### ISSUE TITLE
Max plus algebra Example 5

### ISSUE THREAD

**Issue by bednarj11** [hurak/hys#1]
I believe the first element x_1 of vector x should be -1 instead of 1.

**Comment by hurak** [comment]
Thanks. You are right, the greatest subsolution to the max-plus equation Ax=b is indeed [-1,-2,0]'. I have already uploaded the corrected version to the repo (the commit a8ce28f). I have not yet re-rendered new HTML yet, I am facing some troubles with that. That is why I will also leave this open.

**Comment by hurak** [comment]
Closed by e6ba96d60386fc564d0252186e39a1f394e99cfa.
